/* ZenPy host for the texmark: the script owns the texture objects.
** Bindings generated by zen_bind.hpp from the C++ signatures. */
#include "host.h"

#include "vm.h"
#include "compiler.h"
#include "module.h"
#include "memory.h"
#include "zen_bind.hpp"

#include <cstdio>
#include <cstdlib>

using namespace zen;

/* Texture(path): native class, instance data = texture id in the host table. */
struct TexData
{
    int id;
    void draw(double x, double y) { host_draw_texture(id, x, y); }
    int width() const { return host_texture_width(id); }
    int height() const { return host_texture_height(id); }
    ~TexData() { host_unload_texture(id); }
};
static TexData *tex_load(VM *vm, const char *path)
{
    int id = host_load_texture(path);
    if (id == 0)
    {
        vm->runtime_error("Texture: cannot load '%s'", path);
        return nullptr;
    }
    TexData *t = new TexData;
    t->id = id;
    return t;
}
/* draw_texture(tex, x, y): the free-function form of the same call. */
static void draw_texture(TexData *t, double x, double y) { host_draw_texture(t->id, x, y); }

static bool call_n(VM *vm, const char *fn, Value *args, int n)
{
    vm->call_global(fn, args, n);
    return !vm->had_error();
}

struct Boot { VM *vm; const char *src; bool booted; };

static bool zen_boot(Boot *b)
{
    Compiler compiler;
    ObjFunc *fn = compiler.compile(&b->vm->get_gc(), b->vm, b->src, "sprites.zen");
    if (!fn)
    {
        fprintf(stderr, "zen: compile failed\n");
        return false;
    }
    b->vm->run(fn);
    return !b->vm->had_error();
}

int main(int argc, char **argv)
{
    char *source = host_read_script(argv[0], "sprites.zen");
    if (!source)
        return 1;

    VM vm;
    vm.open_lib_globals(&zen_lib_base);
    bind::def_class<TexData>(vm, "Texture")
        .ctor<&tex_load>()
        .dtor()
        .method<&TexData::draw>("draw", ZEN_NATIVE_GC_SAFE)
        .method<&TexData::width>("width", ZEN_NATIVE_GC_SAFE)
        .method<&TexData::height>("height", ZEN_NATIVE_GC_SAFE)
        .end();
    bind::def_fn<&draw_texture>(vm, "draw_texture", ZEN_NATIVE_GC_SAFE);
    bind::def_fn<&host_rand>(vm, "rand", ZEN_NATIVE_GC_SAFE);
    bind::def_fn<&host_screen_width>(vm, "screen_width", ZEN_NATIVE_GC_SAFE);
    bind::def_fn<&host_screen_height>(vm, "screen_height", ZEN_NATIVE_GC_SAFE);

    Boot boot = { &vm, source, false };
    TexHost host;
    host.ud = &boot;
    host.add_sprites = [](void *ud, int n, double x, double y) -> bool {
        Boot *b = (Boot *)ud;
        if (!b->booted)
        {
            if (!zen_boot(b)) /* the window exists by now: the script may load textures */
                return false;
            b->booted = true;
        }
        Value args[3] = { val_int(n), val_float(x), val_float(y) };
        return call_n(b->vm, "add_sprites", args, 3);
    };
    host.update_all = [](void *ud, double dt) -> bool {
        Value arg = val_float(dt);
        return call_n(((Boot *)ud)->vm, "update_all", &arg, 1);
    };

    int rc = host_run(argc, argv, "zen", &host);
    free(source);
    return rc;
}
