var s = "Hello World Foo"
print(s.len(), s.sub(0,5), s.find("o"), s.upper(), s.lower())
print(s.split(" "), s.trim(), s.strip(), s.replace("o","0"))
print(s.starts_with("He"), s.startswith("He"), s.ends_with("oo"), s.endswith("oo"))
print(s.char_at(1), s.byte_at(1), s.repeat(2), s.count("o"))
print(s.pad_left(20), s.pad_right(20), s.contains("World"), s.reverse())
print(",".join(["a","b"]), s.lstrip(), s.rstrip(), s.title(), s.capitalize(), s.swapcase())
print(s.isalpha(), s.isdigit(), s.isalnum(), s.isspace(), s.isupper(), s.islower())
print(s.index("o"), s.rfind("o"), s.rindex("o"))
print(s.center(21), s.ljust(20), s.rjust(20), "7".zfill(3))
print("a\nb".splitlines(), s.rsplit(" "), s.partition(" "), s.rpartition(" "))
var a = [5,3,1]
a.push(9); a.append(7); print(a.pop(), a.len())
a.remove(0); a.insert(0, 4); print(a.slice(0,2), a.reverse(), a.contains(3))
print(a.join("-"), a.sort(), a.index_of(3), a.count(3), a.copy(), a.extend([8]))
a.clear(); print(a.len())
var m = {"x": 1, "y": 2}
m.set("z", 3); print(m.get("x"), m.has("y"), m.keys(), m.values(), m.items(), m.size())
print(m.update({"w": 4}), m.setdefault("v", 5), m.pop("z"), m.copy())
m.delete("x"); m.clear(); print(m.size())
var t = set([1,2,3])
t.add(4); print(t.has(1), t.size(), t.values(), t.discard(4), t.remove(3))
print(t.issubset(set([1,2,3])), t.issuperset(set([1])), t.isdisjoint(set([9])))
print(t.union(set([7])), t.intersection(set([1])), t.difference(set([2])), t.symmetric_difference(set([1,9])), t.copy())
t.clear(); print(t.size())
var b = Int32Array(4)
b.fill(3); print(b.len(), b.byte_len(), b.tolist(), b.copy().len(), b.slice(0,2).len(), b.type_name())
