s = "Hello, World"
print(len(s), s[0], s[-1], s[7:], s[:5], s[::2], s[::-1], s[2:9:3])
print(s.upper(), s.lower(), s.title(), s.swapcase(), s.capitalize())
print(s.find("o"), s.find("o", 5), s.find("z"), s.rfind("o"), s.index("W"), s.count("l"))
print(s.replace("l", "L"), s.replace("l", "L", 1), s.split(", "), s.split(), "a,b,,c".split(","))
print("  pad  ".strip(), "  pad  ".lstrip(), "  pad  ".rstrip(), "xxhixx".strip("x"))
print(s.startswith("Hell"), s.endswith("d"), s.startswith("x"), "abc".endswith(""))
print("-".join(["a", "b", "c"]), "".join(["x", "y"]), ", ".join([]))
print("abc" * 3, "ab" + "cd", "a" in s, "z" in s, "" in s)
print("Hello" == "Hello", "a" < "B", "abc" != "abd", "hello".isalpha(), "123".isdigit(), "a1".isalnum(), " ".isspace())
print(str(42), str(3.5), str(True), str(None), str([1, "a"]), str((1, 2)), str({"k": 1}))
print(repr("hi"), repr('it\'s'), repr("a\nb"), repr(1.0), repr([1, 'x']))
print("%d %s %.2f %5d|%-5d|%05d %x %o %e" % (42, "s", 3.14159, 7, 7, 7, 255, 8, 12345.678))
print("%s and %r" % ("str", "str"), "%%" % (), "%3s|%-3s|" % ("a", "b"), "%c" % 65)
name = "Zen"; n = 3; f = 2.5
print(f"{name} {n} {f} {n * 2} {f:.3f} {n:04d} {name!r} {name:>6}|{name:<6}|{name:^7}|")
print(f"{'nested'} {[1, 2]} {{literal}} {n + f} {(lambda: 1)()} {n if n > 2 else 0}")
print("{} {} {}".format(1, "two", 3.0), "{0}{1}{0}".format("a", "b"), "{x}-{y}".format(x=1, y=2), "{:>5}|{:<5}|{:^5}|".format("r", "l", "c"))
print("{:.2f} {:d} {:5.1f} {:,} {:b} {:x} {:X} {:e}".format(3.14159, 42, 2.25, 1234567, 5, 255, 255, 1234.5))
print(ord("A"), chr(66), ord("é"), chr(233), "é".encode("utf-8") if False else len("héllo"))
print("a\tb\\n", 'single "double"', "double 'single'", """triple
line""", r"raw\n")
print("abc"[1:2], "abc"[5:], "abc"[-2:], "abc"[:-1], "x"[0:0])
print("Hello".center(11, "*"), "7".zfill(3), "-7".zfill(4), "ab".ljust(4, ".") + "|", "ab".rjust(4) + "|")
print("a b  c".split(" "), "a\nb\r\nc".splitlines(), "one two".partition(" "), "k=v=w".split("=", 1))
print("Hello World".split("o"), list("abc"), sorted("cba"), "".join(reversed("abc")))
print("aXbXc".rsplit("X", 1), "x".join("abc"), "abc".find(""), "ABC".lower() == "abc")
print(str(1.0), str(10.0), str(1e100), str(1.5e-10), str(-0.0), str(123456.789))
print(len(""), "" == "", "abc" + "", "a" * 0 + "b", "abc" > "ab")
print("%s" % [1, 2], "%s" % None, "%s" % 1.5, "%d" % 3.7, "%i" % True)
print("ß".upper(), "ǅ".lower(), "ﬁ".upper() if False else "fi", "İ".lower() if False else "i")
print(int("0x1f", 16), int("101", 2), int("  42  "), float("  2.5 "), int("1_000"))
print(hex(255), oct(8), bin(5), hex(-1))
print("é" in "café", "café".index("é"), "café"[3], len("日本語"), "日本語"[1])
